---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: update packages
      apt:
        update_cache: yes
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/cron.yml
